### ISSUE TITLE
bundle option not working with globs

### ISSUE THREAD

**Issue by reinaldoarrosi** [stealjs/steal-tools#633] opened 2017-03-15 18:14 UTC
Steps to reproduce:
1. git clone https://github.com/stealjs/progressive-loading
2. change "bundle" option in package.json from
```javascript
"bundle": [
      "app/homepage",
      "app/signup",
      "app/login"
    ]
```

to

```javascript
"bundle": 'app/*'
```
3. npm run build

The output in ./dist/bundles does not contain bundles for all modules in app/*.
According to the docs (http://stealjs.com/docs/config.bundle.html#glob-) this should work.

**Comment by matthewp** [comment] 2017-03-15 18:16
Yeah, known issue. Think this is a duplicate of https://github.com/stealjs/steal-tools/issues/507

There's https://github.com/stealjs/steal-tools/pull/512 which is the start of a fix.

**Closed** 2017-03-29 15:21 UTC
