### ISSUE TITLE
Libraries in UMD format cause "Multiple defines for anonymous module" run-time error

### ISSUE THREAD

**Issue by isadovskiy** [stealjs/steal-tools#451] opened 2016-04-22 20:35 UTC
Hello.

I've faced "Multiple defines for anonymous module" run-timeerror when tried to bundle library in UMD format. In dev mode, everything works fine. But after bundling with build-tools I just get this error.

Specifically I'm trying to bundle https://github.com/desandro/masonry/

I tried to get deeper into the issue and here are my findings. Masonry itself is in UMD format. It also depends on several other libraries, which are also in UMD format. It looks like this: https://github.com/umdjs/umd/blob/master/templates/returnExports.js

I'm using ES6 modules format so in dev mode it fallbacks to EJS export syntax. Everything works fine. But when I'm bundling everything with steal-tools, two dependent libraries are incorrectly converted from UMD format. While, for example, Masonry is correctly turned by build-tools from https://github.com/desandro/masonry/blob/master/masonry.js to:

```
(function (window, factory) {
    if (typeof define == 'function' && define.amd) {
        define('masonry-layout@4.0.0#masonry', [
            'outlayer/outlayer',
            'get-size/get-size'
        ], factory);
    } else if (typeof module == 'object' && module.exports) {
        module.exports = factory(require('outlayer'), require('get-size'));
    } else {
        window.Masonry = factory(window.Outlayer, window.getSize);
    }
}(window, function factory(Outlayer, getSize) {
```

While two of its dependency libraries (specifically https://github.com/metafizzy/ev-emitter/blob/master/ev-emitter.js and https://github.com/desandro/matches-selector/blob/master/matches-selector.js) and converted into something like:

```
define('desandro-matches-selector@2.0.1#matches-selector', function (require, exports, module) {
    (function (window, factory) {
        'use strict';
        if (typeof define == 'function' && define.amd) {
            define(factory);
        } else if (typeof module == 'object' && module.exports) {
            module.exports = factory();
        } else {
            window.matchesSelector = factory();
        }
    }(window, function factory() {
```

As a result, two anonymous `define` functions appear in the code (`define(factory);`), which cause the mentioned error. looks like UMD detection code in steal-tools should be improved.

**Comment by isadovskiy** [comment] 2016-04-22 21:18
Looks like the problem is in this line:
````
define(factory);
````
steal-tools does not recognize it as AMD module. Changing it to
````
define(function () {
    return factory();
});
````
makes the things compiled correctly. So can you fix steal-tools to support first syntax?

**Comment by matthewp** [comment] 2016-04-22 21:45
It looks like this module was detected as a commonjs module.  if you force it to be amd with config it will provide work:

```json
"system": {
  "meta": {
    "desandro-matches-selector": {
      "format": "amd"
    }
  }
}
```

we should do a better job of detecting UMD though.

**Comment by isadovskiy** [comment] 2016-04-22 22:00
This is the first thing I tried this but it did not work. I think it's because another issue I found while researching the problem descried above. During research. I tried to substitute Masonry's dependencies with the fixed local versions. Something like
````
        "paths": {
            "ev-emitter": "./src/vendor/ev-emitter/ev-emitter.js",
            "desandro-matches-selector": "./src/vendor/matches-selector/matches-selector.js"
        },
````
But steal-tools just ignores these settings... Until I added them as a dependencies to my package.json explicitly.So looks like steal at the moment does not allow to override dependency's dependencies from package.json.

I will try your solution now one more time, having these sub-libraries added into my package.json

**Comment by isadovskiy** [comment] 2016-04-22 22:05
No, it does not work. It says:
````
Potentially unhandled rejection [5] ReferenceError: Error loading "desandro-matches-selector@2.0.1#matches-selector" at file:D:/Work/site-html/node_modules/desandro-matches-selector/matches-selector.js
Error loading "desandro-matches-selector@2.0.1#matches-selector" from "all" at file:D:/Work/site-html/demo/temp/bundles/all/all.js
Error evaluating file:D:/Work/site-html/node_modules/desandro-matches-selector/matches-selector.js
window is not defined
    at file:D:/Work/site-html/node_modules/desandro-matches-selector/matches-selector.js:24:4
````

**Comment by debone** [comment] 2016-08-09 20:34
Anything on this? I am trying to use the same lib and running into the same problems... Tried many and many stuff and still stuck and no idea how to fix... 

I installed it from npm where is called `masonry-layout`... is it `masonry-layout` problem or a `steal-tools` problem?

---

Tried

```json
"desandro-matches-selector": {
  "format": "amd"
}
```

but it didn't help...

**Comment by matthewp** [comment] 2016-08-09 20:57
Try "format": "global" instead.

**Comment by debone** [comment] 2016-08-09 21:20
Tried 

```json
"desandro-matches-selector": {
  "format": "amd"
}
```

and got on the bundle file

```javascript
define('desandro-matches-selector@2.0.1#matches-selector', function (require, exports, module) {
  (function (global) {
    (function (window, factory) {
      'use strict';
        if (typeof define == 'function' && define.amd) {
          define(factory);
        } else if (typeof module == 'object' && module.exports) {
          module.exports = factory();
        } else {
          window.matchesSelector = factory();
        }
      }(window, function factory() {
     ...
```

Then, I tried 

```json
"desandro-matches-selector": {
  "format": "global"
}
```

and got the same results.

**BUT**

I found this line on the build 

```json
WARN: Could not find desandro-matches-selector in node_modules. Ignoring.
```

so then I tried the name steal-tools generates

```json
"desandro-matches-selector@2.0.1#matches-selector": {
  "format": "amd"
}
```

and steal-tools actually detected it and changed the module format!

Tough now it breaks the build with `window is not defined` and on the `global` format breaks in other ways but in the browser :eyes:

**Comment by isadovskiy** [comment] 2016-08-09 21:23
@debone I fixed it by downloading the libraries, fixing its code and making them a part of my repo.

**Comment by debone** [comment] 2016-08-09 21:25
There is another dependency from `Masonry` that is breaking the same way `ev-emitter`

Got it working by using steal-tools generated name on `package.json` for both

```json
"desandro-matches-selector@2.0.1#matches-selector": {
  "format": "global"
},
"ev-emitter@1.0.3#ev-emitter": {
  "format": "global"
}
```

**Comment by isadovskiy** [comment] 2016-08-09 21:26
Yes, I downlaoded and fixed both - matches-selector and ev-emitter

**Comment by debone** [comment] 2016-08-09 21:33
@isadovskiy it was helpful, I done that and it worked, but I was disappointed :disappointed: and it turns out it can be fixed on steal-tools instead

**Comment by isadovskiy** [comment] 2016-08-09 21:38
Yes, great catach, @debone! Will make a note to use this trick ahead. But the issue is the version of the dependency should be frozen somehow (with npm shrinkwrap for example). Since if you get upgraded library with the next `npm install`, steal config will appear inaccurate. So take care about.

**Comment by pYr0x** [comment] 2016-08-09 22:11
@isadovskiy @debone this happens also with steal 1.0 beta?

**Comment by debone** [comment] 2016-08-10 18:52
@pYr0x Forgive my ignorance, is there grunt tasks on 1.0 beta version? I'm using Grunt and I can't make it work

**Comment by pYr0x** [comment] 2016-08-10 19:01
What do you mean with a grunt task? You can create your own task by using the the steal-tools stream http://stealjs.com/docs/steal-tools.guides.streams.html

**Comment by debone** [comment] 2016-08-10 19:42
I was using Grunt tasks that steal-tools defined and apparently 1.0 beta doesn't have them. 

I could make the streams way work and confirmed that it **has the same** behavior. It looks for `desandro-matches-selector@2.0.1#matches-selector` in the configuration and not `desandro-matches-selector`.

**Comment by debone** [comment] 2016-08-10 20:03
@matthewp Shouldn't `steal-tools` look for `desandro-matches-selector` instead of the versioned name in `package.json`?

**Comment by pYr0x** [comment] 2016-08-10 20:23
@matthewp I think the main problem is the wrong detection of the umd module? The meta data is an other problem ?

**Comment by matthewp** [comment] 2016-08-10 20:29
Honestly I don't know what the problem is :)  The issue has gotten so long that I can't really follow it.  @pYr0x did do some AMD detection fixes so maybe that's it, not sure. A small test case would be nice if not.

**Comment by debone** [comment] 2016-08-11 16:55
There is one issue about the non optimal AMD detection, and Steal-tool looking for the generated name with the version `desandro-matches-selector@2.0.1#matches-selector` instead of the module name `desandro-matches-selector` in the `package.json`. This happens when it is a submodule of a project module. I don't know if it is a problem or expected behavior.

Test case for the second:

Use this lines on `package.json`

```json
"scripts": {
  "build": "steal-tools"
},
"main": "index.js",
"dependencies": {
  "jquery": "^3.1.0",
  "steal": "^0.16.34",
  "steal-tools": "^0.16.6",
  "masonry-layout": "4.1.0"
  },
"system": {
  "meta": {
    "ev-emmiter": {
      "format": "global"
    },
    "ev-emitter@1.0.3#ev-emitter": {
      "format": "global"
    }
  }
}
```

And `index.js`

```javascript
import $ from "jquery";
import "masonry-layout";
```

Then run

```bash
$ npm i
$ npm run build
```

You will observe this line

```bash
WARN: Could not find ev-emmiter in node_modules. Ignoring.
```

But the line about not finding `ev-emitter@1.0.3#ev-emitter` is not there because `steal-tools` can find it.

**Comment by pYr0x** [comment] 2016-08-11 17:06
@debone what about my 1. issue? usually steal should detect the module itself and you dont have to provide a `format` in the package.json

**Closed** 2017-04-13 19:02 UTC
