### ISSUE TITLE
Config included in production build.

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#350] opened 2016-01-09 10:15 UTC
I see that steal-tools include in main bundle all the package.json with resolved dependendcies and other extended stuff with paths etc. Does it even need this?

**Comment by justinbmeyer** [comment] 2016-01-09 16:10
It needs it for the included dependencies. You can use npmIgnore to remove the ones you don't need.

**Comment by whitecolor** [comment] 2016-01-09 16:25
it includes sytem paths, for example:
```
'name': 'jquery',
            'version': '2.1.4',
            'fileUrl': 'file:d:/Dropbox/Code/.../client/node_modules/jquery/package.json',
            'main': 'dist/jquery.js',
            'globalBrowser': {},
            'browser': {}
```
So it makes builds of the same code base different on different machines.
I think such things should be removed.

**Comment by matthewp** [comment] 2016-02-14 23:05
Yeah, this is weird, should figure out a way to prevent the file system path from being included.

**Comment by matthewp** [comment] 2016-02-14 23:07
Oh, this is a dupe of #198

**Closed by matthewp** 2016-02-14 23:07 UTC
Labels: bug

**Comment by whitecolor** [comment] 2016-02-15 09:04
Hm I've already forgot that made those issue!
