### ISSUE TITLE
New steal version can't build functional version of CanJS

### ISSUE THREAD

**Issue by HiFiSamurai** [stealjs/steal-tools#247] opened 2015-05-04 19:19 UTC
I have a project which had previously building successfully, using canJS 2.1.3 and stealJS 0.4.0, but after updating to 2.2.4 and 0.8.4 respectively the outputted production JS file does not execute properly.

The only other major change was that under the new canJS version I was able to target an alternate location of canJS source files:

### Old

    "can/*"                                   :"bower_components/canjs/*.js",
    "can/can"                                 :"bower_components/canjs/can.js"

## New

    "can/*"                                   :"bower_components/canjs/steal/can/*.js",
    "can/can"                                 :"bower_components/canjs/steal/can/can.js"

This runs in development normally, and the build tasks completes correctly, but the production.js file (compiled with the bundleSteal option) does not load the can module properly. Any object referencing it during subsequent steals cannot reference it. I have tried marking the module "global", but this does not resolve the issue (it also makes can unsuable in development mode as well). If I omit all files that make use of can it loads fine, and can becomes properly accessible at the window level. From this it would appear that the procedural timing for module loading is not proceeding in the expected order.

I have also noticed that during initialization, the System,baseURL (which I had been using to improve relative path behavior for various resources) does not take on the value specified in the config file until after all files have loaded. This supports the previous theory that initialization timing is invalid.

I can supply additional config and grunt options as needed. Please advise other config areas that may be the cause of these issues.

**Comment by matthewp** [comment] 2015-05-04 19:26
> Any object referencing it during subsequent steals cannot reference it. 

What do you mean by this?  Will need a little more info to help you.

Also if you updated Steal make sure to update Steal-Tools as well, using different versions could do weird things.

**Comment by HiFiSamurai** [comment] 2015-05-04 19:33
I am using steal and steal-tools at version 0.10.2 (disregard previously stated version, as it was originally noticed with that version but has been updated to match current release).

What I mean is that any subsequently stolen controllers and models cannot initialize properly, since the window.can object is not available.

    can.route(":section");
    Uncaught ReferenceError: can is not defined

As stated, if all such files are omitted and only the canJS library files are stolen, then after loading the bundles can.window appears as expected.

**Comment by matthewp** [comment] 2015-05-04 19:36
Shouldn't those controllers and models be stealing "can" anyways?  It sounds like you had a timing issue that just happened to work before, the fix is not to rely on a global and instead import all of the modules you need.

**Comment by HiFiSamurai** [comment] 2015-05-04 20:00
Hmm, so I can steal the can libraries in every sub-file and it seems to behave better, but that involves a total rewrite of large parts of my codebase. It will also break some custom extensions and convenience utilities for the library.

The bigger issue seems to be that 'can' can't be stolen as a global. When I configure it that way it fails in development mode, seemingly because while "window.can" exists globally, any nested steals fail to attach to the global scope.

    "can/can": {
         format: "global"
    },
    "can/*": {
        format: "global"
    }


    can.route(":section");
    Uncaught TypeError: can.route is not a function

I am tempted to revert back to the top-level canJS files, and attempt to resolve the issues I had with them after updating the steal version. This will complicate the process of stealing and building views, but it's better than what I have now.

**Comment by matthewp** [comment] 2015-05-04 20:09
can isn't a global so marking it as a format: global won't do what you want.  I really suggest fixing your modules to depend on can if they use them. Another thing you could do, but I won't recommend, is still can first, in your main and then dynamically import everything else. Something like:

```js
steal('can', function(can){
  window.can = can;
  System.import("real/main");
});
```

again, would be a better use of your time to just import can.

**Comment by HiFiSamurai** [comment] 2015-05-04 20:28
Hmm, well, I played with the idea of manually declaring window.can, but it creates the same level of re-structuring that importing it regularly would, so I suspect I will have to bite the bullet and just re-structure every module. My concern then becomes, what config changes will be needed by the time the next version roles out?

One of my pet-peaves with this system is things that work in development suddenly become completely invalid in production, which implies a less than perfect mirroring of application code between the two modes. If this was an invalid pattern it would have been beneficial to have it come to light much earlier. Though given the maturing nature of the two libraries in question, such issues are to be expected I suppose.

That's neither here nor there. Thanks for the assistance anyways.

**Comment by matthewp** [comment] 2015-05-04 23:07
The reason for that is when you bundle the modules together they are ordered based on what their dependencies are. So that means if you have a lot of modules depending on `can`, `can` will be ordered towards the top.  In development it's likely that as long as one of your top-level modules is dependent on `can`, then `window.can` will exist before any of those modules are fetched.

If you prefer to have development/production be the same we have a watch mode with steal so that you are effectively using production all of the time. With source-maps it works fairly well.  It might be a good thing to try until you get your dependency issue worked out, anyways.  http://stealjs.com/docs/steal-tools.guides.watch_mode.html

**Comment by matthewp** [comment] 2015-05-11 17:28
Closing as this is not a bug.

**Closed by matthewp** 2015-05-11 17:28 UTC
