### ISSUE TITLE
Using steal-export, cannot set outputs.ignore to regex

### ISSUE THREAD

**Issue by lukewhyte** [stealjs/steal-tools#239] opened 2015-04-29 01:08 UTC
It seems that in the parse method on line 83 of npm-utils.js, we're trying determine if ignore's value is a npm-like modulename, in turn, assuming that it is a string.

**Comment by matthewp** [comment] 2015-04-29 01:15
This is probably caused by the logic that converts ignores to npm style module names, but we just shouldn't be doing the conversion if the ignore is a non-string.

**Comment by matthewp** [comment] 2015-05-11 17:29
Fixed by #245

**Closed by matthewp** 2015-05-11 17:29 UTC
Labels: bug
