### ISSUE TITLE
watch out for global elements in global-shim

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal-tools#479] opened 2016-06-24 02:30 UTC
A page like:

```
<div id='repos'/>
<script src="//code.jquery.com/jquery-3.0.0.js"></script>
<script src="../dist/global/repos.js"></script>
<script>
    repos("#repos");
</script>
```

Where I built `repos.js` like:

```
    "+global-js": {
        exports: {
            "myhub/repos/repos":"repos",
            "jquery": "jQuery"
        },
        dest: __dirname+"/dist/global/repos.js"
    }
```

doesn't work because there's a global `#repos` element.  So `repos` the function never gets defined.

I think this is a bug.  We might want to check for this situation. Why aren't we setting no matter what?

**Comment by matthewp** [comment] 2016-06-24 02:37
I think it was because exports is used for both importing modules already on the global and for exporting modules onto the global.  The check was used to guess that it's intended to be an export onto the global.  What happens if there's a jquery module included but jQuery is already in the page?  we overwrite it?  Maybe.

**Comment by matthewp** [comment] 2017-04-13 19:02
Closing, this is as designed.

**Closed by matthewp** 2017-04-13 19:02 UTC
