### ISSUE TITLE
bundleAssets sets bundlesPath incorrectly when true

### ISSUE THREAD

**Issue by akagomez** [stealjs/steal-tools#491] opened 2016-07-07 23:15 UTC
If `bundleAssets` and `bundleSteal` are both `true`, the `bundlesPath` is adversely affected. 

Example:

```
var stealTools = require('steal-tools');

var buildPromise = stealTools.build({
  config: __dirname + '/../package.json!npm',
  bundlesPath: __dirname + '/../dist/bundles'
},{
  bundleAssets: true,
  bundleSteal: true
});

module.exports = buildPromise;
```

Results in:

```
if(typeof steal === "undefined") steal = {};
steal.bundlesPath = "bundles";
/*[production-config]*/
```

With `bundleAssets` set to `false`, `bundlesPath` is no longer configured at the top of the built/main file and Steal is left to derive `bundlesPath` on it its own, correctly.

**Comment by pYr0x** [comment] 2016-07-08 07:14
@akagomez thx,
can you add a breaking test in a new branch?

**Comment by matthewp** [comment] 2016-07-08 10:57
I'm not sure if this is a bug or not. The primary use-case of bundleAssets is to distribute the `dist` folder as your entire app, such as on a CDN. It was actually built for the CDN aspect of DoneJS.

Maybe instead bundleAssets could take an option that lets you specify the bundlesPath yourself.

**Comment by akagomez** [comment] 2016-07-08 11:59
I see. That makes sense. 

I set `bundlesPath` alongside `bundleAssets` and it had no effect. Only when I provided `bundles-path` as a script attribute was I able to override the `bundleAssets` `bundlesPath`. 

If you asked me, setting one option shouldn't interfere with another. For the case of CDN's and DoneJS I would think you would have to set both options to get the intended outcome.

**Comment by matthewp** [comment] 2016-07-08 12:38
The problem is that bundlesPath means two different things, one during the build and one in production. 

In the build it means "where should bundle be written to in the filesystem".

In production it means "what path, relative to the baseURL, should I fetch bundles".

In this case, bundleAssets is setting the latter bundlesPath to what it thinks you want (because that's what bundleAssets is for). There is no way to manually set the latter bundlesPath (the path to look from in production). 

We should probably get rid of the confusion here and move the first meaning of "bundlesPath" to another option, maybe `buildOptions.dest` or something like that. Then setting bundlesPath would set the bundlesPath like it should, something like:

```js
stealTools.build({
  config: __dirname + "/package.json!npm"
}, {
  bundleSteal: true,
  bundlesPath: "/my-page/bundles",
  dest: __dirname + "/path/to/my/bundles"
});
```

This would write out the bundles to the `dest` and configure steal to look for them at `/my-page/bundles` in production.

**Comment by matthewp** [comment] 2016-07-08 12:39
Going to mark this as 1.0 as I think this is a good thing to fix while we have the ability to break things.

**Comment by pYr0x** [comment] 2016-07-08 18:28
@matthewp i can take this. do you have time to talk about it? i can do some stuff at the weekend.

**Comment by matthewp** [comment] 2016-07-08 18:47
Yeah, I'm around.

**Comment by matthewp** [comment] 2016-07-08 19:16
```js
stealTools.build({

}, {
  bundleSteal: false,
  bundlesPath: "/")
}).then(null, function(err){
  // err.message => Cannot use bundlesPath without bundleSteal: true
});
```

**Comment by pYr0x** [comment] 2016-07-08 19:24
- [ ] check dest for files in dest folder
- [ ] check bundlesPath in build options and check loading
- [ ] throw an error if bundleSteal is provided and bundlePaths not, or other

**Comment by matthewp** [comment] 2016-09-01 15:53
@pYr0x still plan on taking this one or is it free now?

**Comment by pYr0x** [comment] 2016-09-01 16:30
@matthewp if you want to take it.. ok :) i will need some time because i am busy at the moment

**Comment by matthewp** [comment] 2016-09-01 16:37
I'm not necessarily going to take it now, just want to free it up for others.

**Comment by matthewp** [comment] 2016-11-08 16:15
The new `dest` option is in major, so this is closed by https://github.com/stealjs/steal-tools/pull/548.  Will do a release for this.

**Closed by matthewp** 2016-11-08 16:15 UTC
Labels: enhancement, feature, in progress, P2
