### ISSUE TITLE
steal-tools build bricks with d3 v4

### ISSUE THREAD

**Issue by bkrrr** [stealjs/steal-tools#519] opened 2016-08-31 22:42 UTC
Hello,

i think, this problem affects all imports written with ECMAScript 6 modules.

i have a page with d3, and i moved from v3 to v4. D3 v4 is written in modules and can be used during development without any problems.

steal-tools generates invalid code, as far as i can say the generated define statements look like (in main.js):
```
define('d3@4.2.2#build/d3', Color, color, {
        displayable: function () {
            return this.rgb().displayable();
        },
        toString: function () {
            return this.rgb() + '';
        }
    });
```
The first parameter doesn't match with the method itself (in main.js):
```
function define(constructor, factory, prototype) {
        constructor.prototype = factory.prototype = prototype;
        prototype.constructor = constructor;
    }
```
here is an example:
https://github.com/bkrrr/bugExample

grunt con
=> normal 
http://localhost:9001/index.html
=> productive build
http://localhost:9001/indexp.html

**Comment by pYr0x** [comment] 2016-09-01 07:37
@bkrrr do you tried the steal and steal-tools 1.0 RC version?

**Comment by bkrrr** [comment] 2016-09-01 08:56
Yes, happens there as well,

btw. steal-tools 1.0 rc is missing the task folder. I copied /tasks/ from 0.16.7 to make is runnable with grunt.

**Comment by matthewp** [comment] 2016-09-01 10:49
Thanks for the test project.

**Comment by matthewp** [comment] 2016-09-01 13:29
Going to look at this today.

**Comment by matthewp** [comment] 2016-09-01 15:19
@bkrrr the Grunt tasks have been moved to https://github.com/stealjs/grunt-steal for 1.0

**Comment by matthewp** [comment] 2016-09-01 15:41
Hey, the issue is that the file is a global that looks like AMD. You can configure this with meta:

```js
"system": {
  "meta": {
    "d3": {
      "format": "global"
    }
  }
}
```

Also, if you decide to use 1.0 you have to include the project name in your production html file like `main="bugsteal/main"`, but in 0.16 you don't have to do this.

Closing as nothing we can do here.

**Closed by matthewp** 2016-09-01 15:41 UTC
Labels: bug
